In [22]:
import numpy as np
import pandas as pd
import np_utils
import keras

In [23]:
# Our data
X = np.array([[0,0],[0,1],[1,0],[1,1]]).astype('float32')
y = np.array([[0],[1],[1],[0]]).astype('float32')

# One-hot encoding the output
y = keras.utils.np_utils.to_categorical(y, nb_classes=None)

In [24]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [25]:
y

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [26]:
# Initial Setup for Keras
from keras.models import Sequential
from keras.layers.core import Dense, Activation

In [27]:
# Building the model
xor = Sequential()

In [28]:
# Add required layers
xor.add(Dense(64,input_dim=2))
#第二层 - 添加 softmax 激活层
xor.add(Activation('relu'))
#新加一层
xor.add(Dense(8))
#第三层 - 添加全连接层
xor.add(Dense(2))
#第四层 - 添加 softmax 激活层
xor.add(Activation('sigmoid'))

In [29]:
xor.compile(loss="categorical_crossentropy", optimizer="adam", metrics = ['accuracy'])

In [30]:
xor.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
dense_5 (Dense)                  (None, 64)            192         dense_input_3[0][0]              
____________________________________________________________________________________________________
activation_5 (Activation)        (None, 64)            0           dense_5[0][0]                    
____________________________________________________________________________________________________
dense_6 (Dense)                  (None, 8)             520         activation_5[0][0]               
____________________________________________________________________________________________________
dense_7 (Dense)                  (None, 2)             18          dense_6[0][0]                    
___________________________________________________________________________________________

In [31]:
xor.fit(X, y, nb_epoch=1000, verbose=0)

# Scoring the model
score = xor.evaluate(X, y)
print("\nAccuracy: ", score[-1])

# Checking the predictions
print("\nPredictions:")
print(xor.predict_proba(X))

4/4 [==============================] - 0s

Accuracy:  1.0

Predictions:
4/4 [==============================] - 0s
[[7.9055905e-01 9.7883295e-04]
 [6.7317967e-05 1.3740048e-01]
 [9.1419170e-05 1.7613278e-01]
 [8.5398920e-02 3.4833258e-05]]
